apiVersion: v1
kind: Service
metadata:
  name: game-svc
  labels:
    app: game
spec:
  type: NodePort
  ports: 
  - port: 8080
    nodePort: 31003 
  selector:
    app: game    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-deployment
  labels:
    app: game
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game11
        image: rghorpade80/gameoflife:latest
        ports:
        - containerPort: 8080
